import { OFFICIAL_SOURCES } from "./sources.js";

export const SUPPORT_URL = "https://buymeacoffee.com/ashleysnl";

export const TOOLTIPS = {
  province: {
    term: "Province",
    plain: "Your province changes estimated provincial tax and benefit context.",
    why: "Taxes can materially change retirement income needs.",
    range: "All Canadian provinces are available. Default: NL.",
    example: "A plan in NL may estimate a different tax burden than the same income in ON.",
  },
  birthYear: {
    term: "Year of birth",
    plain: "Used to estimate your age each year in the projection.",
    why: "Age controls CPP/OAS start timing and retirement duration.",
    range: "Typical range: 1940-2008.",
    example: "Born in 1985 means age 65 in 2050.",
  },
  retirementAge: {
    term: "Retirement age",
    plain: "Age when your plan switches from saving to drawing income.",
    why: "Earlier retirement means fewer saving years and longer drawdown years.",
    range: "Typical range: 55-70.",
    example: "Retiring at 60 instead of 65 increases years your savings must support.",
  },
  lifeExpectancy: {
    term: "Life expectancy",
    plain: "How long the model projects your retirement spending.",
    why: "Longer horizon requires more assets or lower annual spending.",
    range: "Typical planning range: 85-100.",
    example: "Planning to age 95 tests longevity risk.",
  },
  desiredSpending: {
    term: "Desired retirement spending",
    plain: "Your annual after-tax spending goal in today’s dollars.",
    why: "This is the target your income sources and savings must cover.",
    range: "Varies by household and location.",
    example: "$60,000 today at 2% inflation is about $73,000 in 10 years.",
  },
  inflation: {
    term: "Inflation",
    plain: "Annual increase applied to future spending and optionally tax brackets.",
    why: "Higher inflation can raise the long-term draw required from savings.",
    range: "Typical long-term assumption: 1.5%-3.0%.",
    example: "At 2%, costs roughly double in about 36 years.",
  },
  currentSavings: {
    term: "Current total savings",
    plain: "Your starting investable balance across all accounts.",
    why: "Starting balance is a major driver of retirement readiness.",
    range: "Any non-negative value.",
    example: "$200,000 today compounds over your remaining working years.",
  },
  annualContribution: {
    term: "Annual contribution",
    plain: "How much you add to savings each year before retirement.",
    why: "Regular contributions can significantly increase retirement assets.",
    range: "Any non-negative value.",
    example: "$8,000 per year for 20 years adds $160,000 before growth.",
  },
  contributionIncrease: {
    term: "Contribution increase (%/year)",
    plain: "Annual percentage increase applied to your savings contribution before retirement.",
    why: "Gradually increasing contributions can materially improve retirement readiness.",
    range: "Typical range: 0%-5% per year.",
    example: "A $10,000 contribution growing 3% yearly becomes about $13,439 in year 10.",
  },
  capitalInjectAmount: {
    term: "Lump-sum amount",
    plain: "A one-time amount added to investable assets at a specific age.",
    why: "Large one-time proceeds can materially improve retirement sustainability.",
    range: "Any non-negative value.",
    example: "Downsizing a home might add a $150,000 one-time injection at age 67.",
  },
  capitalInjectAge: {
    term: "Lump-sum age",
    plain: "The age when the one-time capital injection is received.",
    why: "Timing changes compounding and how long the capital supports spending.",
    range: "Typical planning range: 50-95.",
    example: "A lump sum at 60 has more time to compound than the same amount at 75.",
  },
  riskProfile: {
    term: "Risk profile",
    plain: "Maps to default long-term return assumptions.",
    why: "Expected returns directly affect projected balances.",
    range: "Conservative, Balanced, Aggressive.",
    example: "Balanced defaults near 5.5% nominal annual return.",
  },
  pensionAmount: {
    term: "Workplace pension amount",
    plain: "Annual pension income before tax once it starts.",
    why: "Guaranteed income reduces withdrawal pressure on savings.",
    range: "Depends on pension plan terms.",
    example: "$18,000/year pension can cover a meaningful baseline of spending.",
  },
  pensionStartAge: {
    term: "Pension start age",
    plain: "Age pension payments begin.",
    why: "Later starts create more early-retirement funding needs.",
    range: "Typical range: 55-70.",
    example: "If pension starts at 65 but retirement is 60, savings bridge 5 years.",
  },
  cppAmount65: {
    term: "CPP estimate at 65",
    plain: "Estimated annual CPP amount if started at age 65.",
    why: "CPP is a core retirement income source for many Canadians.",
    range: "Personal estimate from Service Canada statements.",
    example: "$12,000/year at 65 can change with early or late start.",
  },
  cppStartAge: {
    term: "CPP start age",
    plain: "Age you plan to start CPP (60-70).",
    why: "Starting earlier lowers annual amount; delaying raises it.",
    range: "Allowed range: 60-70.",
    example: "Starting at 70 can materially increase annual CPP versus 65.",
  },
  oasAmount65: {
    term: "OAS estimate at 65",
    plain: "Estimated annual OAS amount if started at 65.",
    why: "OAS contributes to baseline retirement income after 65.",
    range: "Based on residency and eligibility.",
    example: "Delaying OAS can increase annual benefit.",
  },
  oasStartAge: {
    term: "OAS start age",
    plain: "Age you plan to start OAS (65-70).",
    why: "Start timing changes annual OAS amount and clawback exposure.",
    range: "Allowed range: 65-70.",
    example: "Starting at 68 increases annual OAS versus 65.",
  },
  spousePensionAmount: {
    term: "Spouse pension amount",
    plain: "Annual workplace/private pension income for spouse before tax.",
    why: "Spousal guaranteed income can reduce household savings withdrawals.",
    range: "Any non-negative value.",
    example: "A spouse pension of $10,000/year lowers portfolio draw needs.",
  },
  spousePensionStartAge: {
    term: "Spouse pension start age",
    plain: "Age when spouse pension starts.",
    why: "Timing determines how much early-retirement gap remains.",
    range: "Typical range: 55-70.",
    example: "If spouse pension starts at 65, years before 65 need other funding.",
  },
  spouseCppAmount65: {
    term: "Spouse CPP estimate at 65",
    plain: "Estimated annual spouse CPP at age 65.",
    why: "Adds household guaranteed income in retirement.",
    range: "Personal estimate from Service Canada statements.",
    example: "Spouse CPP can materially improve first-year retirement coverage.",
  },
  spouseCppStartAge: {
    term: "Spouse CPP start age",
    plain: "Age spouse plans to start CPP (60-70).",
    why: "Earlier or later start changes annual spouse CPP amount.",
    range: "Allowed range: 60-70.",
    example: "Delaying spouse CPP can increase late-retirement guaranteed income.",
  },
  spouseOasAmount65: {
    term: "Spouse OAS estimate at 65",
    plain: "Estimated annual spouse OAS at age 65.",
    why: "Adds to household baseline retirement income.",
    range: "Based on eligibility and residency history.",
    example: "Spouse OAS can reduce total required account withdrawals.",
  },
  spouseOasStartAge: {
    term: "Spouse OAS start age",
    plain: "Age spouse plans to start OAS (65-70).",
    why: "Start timing affects annual benefit and clawback exposure.",
    range: "Allowed range: 65-70.",
    example: "Starting at 67 gives higher annual OAS than 65.",
  },
  scenarioSpread: {
    term: "Scenario spread",
    plain: "Difference used to create best/base/worst deterministic return scenarios.",
    why: "Helps compare sensitivity to return assumptions.",
    range: "Typical range: 1%-3%.",
    example: "Base 5.5% with spread 2% gives 3.5% worst and 7.5% best.",
  },
  volatility: {
    term: "Volatility",
    plain: "Planning volatility input for education and stress framing.",
    why: "Higher volatility means wider range of possible outcomes.",
    range: "Typical long-term annualized range: 6%-15%.",
    example: "A more volatile portfolio may deviate further from base projections.",
  },
  rrsp: {
    term: "RRSP/RRIF account",
    plain: "Tax-deferred account; withdrawals are generally taxable.",
    why: "Withdrawal order affects taxes and government benefit interactions.",
    range: "Any non-negative value.",
    example: "Large RRSP withdrawals can raise taxable income and clawback risk.",
  },
  tfsa: {
    term: "TFSA account",
    plain: "Tax-free savings account; eligible withdrawals are tax-free.",
    why: "Useful for flexible, tax-efficient retirement cash flow.",
    range: "Any non-negative value.",
    example: "Using TFSA withdrawals can reduce taxable income in high-tax years.",
  },
  nonRegistered: {
    term: "Non-registered account",
    plain: "Taxable investment account outside RRSP/TFSA.",
    why: "Some withdrawal amounts may be taxable depending on gains/income type.",
    range: "Any non-negative value.",
    example: "Capital gains are typically taxed more favorably than full-income withdrawals.",
  },
  cash: {
    term: "Cash account",
    plain: "Liquid cash reserve for short-term spending needs.",
    why: "Can reduce forced selling during market stress.",
    range: "Any non-negative value.",
    example: "A cash buffer can help cover 1-2 years of spending gaps.",
  },
  kpiBalanceRetirement: {
    term: "Balance at retirement",
    plain: "Estimated portfolio value at your retirement age.",
    why: "This is your starting pool for retirement withdrawals.",
    range: "Based on your savings, contributions, returns, and timeline.",
    example: "Higher contributions can lift this value materially.",
  },
  kpiSpendingTarget: {
    term: "After-tax spending target",
    plain: "How much spendable cash you want in retirement.",
    why: "This is the benchmark income your plan needs to deliver.",
    range: "Set in guided and advanced inputs.",
    example: "$70,000 means $70,000 to spend after tax.",
  },
  kpiGuaranteedIncome: {
    term: "Guaranteed income",
    plain: "Combined pension, CPP, and OAS available for spending in the year. In summary views this is shown after estimated tax when tax estimates are enabled.",
    why: "This is the portion of spending covered before savings withdrawals are needed.",
    range: "Depends on benefit amounts and start ages.",
    example: "If after-tax guaranteed income covers most spending, required withdrawals are lower.",
  },
  kpiCoveragePercent: {
    term: "Guaranteed-income coverage",
    plain: "The share of your after-tax spending target covered by after-tax guaranteed income alone.",
    why: "It shows how dependent the plan is on savings withdrawals.",
    range: "100% means guaranteed income alone covers the full spending target on the same after-tax basis.",
    example: "If after-tax guaranteed income is $45k and spending target is $60k, coverage is 75%.",
  },
  kpiNetGap: {
    term: "Net gap from savings",
    plain: "The after-tax spending shortfall not covered by guaranteed income.",
    why: "This is the net amount your savings must provide.",
    range: "Cannot be below zero.",
    example: "If spending is $60k and guaranteed net is $45k, gap is about $15k.",
  },
  kpiGrossWithdrawal: {
    term: "Gross withdrawal required",
    plain: "The pre-tax RRSP/RRIF withdrawal needed to fund the net gap.",
    why: "Withdrawals are taxable, so gross is often higher than net needed.",
    range: "Depends on taxable income and tax rate in that year.",
    example: "A $20k net gap may require a $26k gross withdrawal.",
  },
  netSpendingAvailable: {
    term: "Net spending available",
    plain: "Total spendable cash flow after estimated tax and clawback for the selected year.",
    why: "This is the amount available to actually fund spending.",
    range: "Usually equals guaranteed income after tax plus net withdrawals.",
    example: "If guaranteed income nets $45k and net withdrawals add $15k, net spending available is $60k.",
  },
  taxDrag: {
    term: "Tax and clawback drag",
    plain: "The portion of gross withdrawals that does not become spendable cash because of estimated income tax and any modeled OAS clawback.",
    why: "This explains why gross withdrawals can be larger than the net spending gap.",
    range: "Zero when tax estimates are disabled or no taxable withdrawal is required.",
    example: "A $28k gross withdrawal with $6k tax/clawback drag leaves about $22k net to spend.",
  },
  registeredAssumption: {
    term: "Registered-only assumption",
    plain: "This dashboard currently treats all savings withdrawals as RRSP/RRIF taxable withdrawals.",
    why: "It makes the tax wedge clear and easier to interpret.",
    range: "TFSA/cash effects are intentionally excluded here.",
    example: "If you had TFSA withdrawals, tax wedge could be smaller than shown.",
  },
  rrifConversionAge: {
    term: "RRIF conversion age",
    plain: "Age when RRSP is treated as RRIF for minimum withdrawal rules.",
    why: "From this age, minimum withdrawals can force taxable income.",
    range: "Typical conversion age: 71.",
    example: "At 71, required RRIF minimums may raise taxable income even if spending is lower.",
  },
  rrifMinimums: {
    term: "RRIF minimum withdrawals",
    plain: "Annual minimum percentage that must be withdrawn from RRIF by age.",
    why: "Can increase taxes and OAS clawback exposure in later retirement.",
    range: "Age-based schedule from CRA.",
    example: "If required minimum exceeds your spending gap, taxable income still rises.",
  },
  oasClawback: {
    term: "OAS clawback",
    plain: "OAS can be reduced when taxable income exceeds the recovery threshold.",
    why: "Higher taxable withdrawals can reduce net OAS received.",
    range: "Calculated using a planning threshold and 15% recovery rate.",
    example: "Large RRIF withdrawals can trigger partial OAS recovery tax.",
  },
  learnInflationCalc: {
    term: "Inflation spending calculator",
    plain: "Shows how a spending amount today grows over time with inflation.",
    why: "Retirement budgets need future-dollar planning, not just today’s prices.",
    range: "Common inflation assumptions are around 1.5%-3.0%.",
    example: "$80,000 today at 2.5% for 10 years is about $102,000.",
  },
  learnTaxGrossUp: {
    term: "Tax gross-up",
    plain: "To receive a net amount after tax, you must withdraw a larger gross amount.",
    why: "This explains why RRSP/RRIF withdrawals can exceed your spending gap.",
    range: "Effective tax rates vary by income and province.",
    example: "If you need $80,000 net and tax is 22%, gross is about $102,564.",
  },
  learnRrifMinimum: {
    term: "RRIF minimum withdrawal",
    plain: "RRIF rules require a minimum annual withdrawal based on age.",
    why: "Minimums can force higher taxable income in later retirement.",
    range: "Starts at age 71 conversion, then rises with age.",
    example: "At age 72, minimum is about 5.40% of RRIF balance.",
  },
  learnOasClawback: {
    term: "OAS clawback estimator",
    plain: "OAS can be reduced when income exceeds the annual recovery threshold.",
    why: "Higher taxable income may reduce government benefits.",
    range: "Recovery tax is 15% of income above threshold (up to full OAS).",
    example: "If income is above threshold, part of OAS is paid back.",
  },
  learnPensionSplit: {
    term: "Spousal pension splitting",
    plain: "Eligible pension income can be shifted between spouses (up to 50%) for tax purposes.",
    why: "Balancing taxable income between spouses can lower total household tax.",
    range: "Split percentage can range from 0% to 50%.",
    example: "Shifting pension from higher-income spouse may reduce combined tax.",
  },
  phaseWeightedSpending: {
    term: "Phase-weighted annual spending",
    plain: "A single average annual spending value based on your Go-Go, Slow-Go, and No-Go years.",
    why: "It summarizes a changing spending path into one planning benchmark.",
    range: "Depends on your base spending, phase percentages, and years in each phase.",
    example: "Higher Go-Go spending and longer Go-Go years raise the weighted average.",
  },
  stressScenario: {
    term: "Stress scenario",
    plain: "A simple what-if case that changes return and inflation assumptions.",
    why: "It helps you see how sensitive your plan is to good or bad environments.",
    range: "Shown as best, base, and downside cases.",
    example: "Downside means lower returns and higher inflation than your base assumptions.",
  },
  stressGapSurplus: {
    term: "First-year gap/surplus",
    plain: "Difference between your retirement spending target and available income in the first retirement year.",
    why: "A gap means savings must fund the shortfall; a surplus gives flexibility.",
    range: "Negative values are gaps, positive values are surpluses.",
    example: "-$8,000 means you need extra savings withdrawals in year one.",
  },
  depletionAge: {
    term: "Depletion age",
    plain: "The age when projected savings reach zero in a scenario.",
    why: "It highlights longevity risk if withdrawals outpace portfolio growth.",
    range: "If assets last through your horizon, depletion is not triggered.",
    example: "Depletion at age 88 means the model runs out of savings at 88.",
  },
  strategyLifetimeTaxes: {
    term: "Estimated lifetime taxes",
    plain: "Total projected taxes paid across your full retirement projection for this strategy.",
    why: "Comparing lifetime tax totals helps evaluate withdrawal order tradeoffs.",
    range: "Planning estimate only; actual taxes will vary by year and rules.",
    example: "A lower lifetime tax total can leave more net spending capacity.",
  },
  strategyLifetimeClawback: {
    term: "Estimated lifetime OAS clawback",
    plain: "Total projected OAS recovery tax across your full retirement projection.",
    why: "Strategies with higher taxable income can increase clawback over time.",
    range: "Zero if income stays below clawback thresholds or OAS is not received.",
    example: "Large RRIF withdrawals can raise lifetime clawback totals.",
  },
  forcedRrifDrawdown: {
    term: "Forced RRIF drawdown",
    plain: "After RRSP converts to RRIF, Canada requires a minimum annual withdrawal.",
    why: "This can increase taxable income and tax even if spending needs are lower.",
    range: "Starts at your RRIF conversion age (commonly 71) and rises with age.",
    example: "At older ages, minimum RRIF withdrawals can exceed your spending gap.",
  },
  oasRiskMeter: {
    term: "OAS clawback risk",
    plain: "A simple Low/Med/High badge based on projected clawback amount.",
    why: "It helps quickly identify if taxable retirement income may reduce OAS.",
    range: "Low: none/minimal, Medium: moderate, High: substantial.",
    example: "High risk suggests withdrawals may be pushing income above clawback thresholds.",
  },
  retirementScore: {
    term: "Retirement plan score",
    plain: "A planning heuristic score from 0-100 based on coverage, longevity buffer, tax drag, clawback exposure, and RRIF shock.",
    why: "It provides a quick directional summary of plan strength and weak spots.",
    range: "Higher is generally better under current assumptions.",
    example: "A low depletion sub-score indicates longevity risk.",
  },
  coverageScoreWeights: {
    term: "Coverage score weights",
    plain: "The score blends coverage ratio, depletion risk, tax drag, clawback exposure, and RRIF shock.",
    why: "It keeps the score transparent and easy to audit.",
    range: "Coverage 35 points, longevity 30, tax drag 15, clawback 10, RRIF shock 10.",
    example: "If your coverage ratio improves, your score usually rises first.",
  },
  cppOasTimingSim: {
    term: "CPP/OAS timing simulator",
    plain: "Previews start-age changes for CPP and OAS without immediately overwriting your plan.",
    why: "Timing affects withdrawals, tax drag, and clawback in different years.",
    range: "CPP ages 60-70 and OAS ages 65-70.",
    example: "Delaying CPP can reduce early cash flow but increase later guaranteed income.",
  },
  rrspMeltdown: {
    term: "RRSP meltdown strategy",
    plain: "A planned early-withdrawal approach from RRSP/RRIF to smooth later taxes.",
    why: "It can reduce future RRIF pressure and potential OAS clawback exposure.",
    range: "Strategy setting only; personal suitability varies.",
    example: "Extra withdrawals before age 71 can reduce forced minimum pressure later.",
  },
};

export const OFFICIAL_REFERENCES = OFFICIAL_SOURCES;

export const PLAN_SUMMARY_ROWS = [
  { key: "province", label: "Province", tooltip: "province" },
  { key: "retirementAge", label: "Retirement age", tooltip: "retirementAge" },
  { key: "desiredSpending", label: "Annual spending target", tooltip: "desiredSpending" },
  { key: "inflation", label: "Inflation", tooltip: "inflation" },
  { key: "returnProfile", label: "Investment return profile", tooltip: "riskProfile" },
  { key: "cpp", label: "CPP income at 65", tooltip: "cppAmount65" },
  { key: "oas", label: "OAS income at 65", tooltip: "oasAmount65" },
  { key: "pension", label: "Private/workplace pension", tooltip: "pensionAmount" },
  { key: "savings", label: "Savings balance", tooltip: "currentSavings" },
  { key: "contribution", label: "Annual contributions", tooltip: "annualContribution" },
];

export const LEARN_PROGRESS_ITEMS = [
  { key: "inflation", label: "Inflation" },
  { key: "income", label: "Income Sources" },
  { key: "taxes", label: "Taxes" },
  { key: "rrif", label: "RRIF Rules" },
  { key: "oas", label: "OAS Clawback" },
  { key: "strategy", label: "Withdrawal Strategy" },
  { key: "stress", label: "Stress Testing" },
];
